[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "harmonyos-dev-mcp"
version = "0.8.0"
requires-python = ">=3.12"
readme = "README.md"
authors = [
    { name = "huduanmu", email = "772927148@qq.com" }
]
dependencies = [
    "fastmcp>=0.1.0",
    "loguru>=0.7.0",
]

[project.scripts]
harmonyos-dev-mcp = "harmonyos_dev_mcp:main"

[tool.hatch.build.targets.wheel]
packages = ["src/harmonyos_dev_mcp"]
